### ISSUE TITLE
FE / BE - User name is not persisting on Profile component re-render after altering/saving user data.

### ISSUE THREAD

**Issue by infamouskeyduster** [rachael-t/Crate#40]
- [ ] determine what is required to 'resave' the user's name to database after user profile is edited…

**Comment by rachael-t** [comment]
Overview of the bug:

- User logs in and navigates to their Profile
- User sees their name being displayed
- User navigates to Edit Profile page
- User clicks the save button (behavior is the same both when changes are made and when changes are not made)
- User is redirected to Profile page and no longer sees their name
- However, the user can log out, log back in, and name appears again (it does not appear it is fully overwritten in the database)

**Comment by rachael-t** [comment]
## Overview of the process to determine issue/fix:

**Started by going through user flow with dev tools open.**
- Reviewed both the user props under both Profile and EditProfile components. The name appeared as expected.
- Reviewed the user object state under EditProfile and saw that the name property was undefined. 
- I understood that when the user clicked saved, the entire user object under the state is sent to the action creator and saved to the store. Since the name property was undefined, it was being resaved that way to the store which is how it's being pulled down under Profile to be displayed.
- Looked at the code under EditProfile - state. Saw a typo. The user property was being defined as this.props.user.name instead of this.props.user.details.name. 
- Fixed the code, went through the user flow in-app to confirm the solution worked, ran testing suite to ensure no fixes were needed on that end.

Screenshots:
<img width="482" alt="Screen Shot 2020-07-12 at 12 19 50 PM" src="https://user-images.githubusercontent.com/54180641/87253861-d55d5680-c43b-11ea-90cb-1dab5325dd40.png">
<img width="558" alt="Screen Shot 2020-07-12 at 12 20 44 PM" src="https://user-images.githubusercontent.com/54180641/87253872-e1491880-c43b-11ea-832a-bd1ad3f398b3.png">
